import Ai from '@/components/orginalcom/AiPage'
import AiSecond from '@/components/orginalcom/AiSecond';
import { getAllCategories  } from '@/lib/actions/category.actions'
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: "Book by Ai",
  description: "Generated by create next app",
};
async function AiPage() {
    // const Categories = await getAllCategories()
    // const location = await getAllLocation()
  
    return (
    <main className=' h-screen overflow-hidden'>
        {/* <Ai categories={Categories } locations = {location}/>  */}
        <AiSecond />
    </main>
  )
}

export default AiPage
 